version: "1.0"
 
services:
    db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: BakeryDB
      environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "SecretPassword123"
        MSSQL_PID: "Developer"
        
      ports:
        - 1433:1433